changelog.html
src/java/com/reucon/openfire/plugin/archive/xep0313/IQQueryHandler0.java
src/java/com/reucon/openfire/plugin/archive/xep0313/IQQueryHandler1.java
src/java/com/reucon/openfire/plugin/archive/xep0313/IQQueryHandler2.java

When there's no 'to' address in the request, the request is to be handled on behalf of
the requesting entity - not on behalf of the domain itself.
This should fix #27 .

27: Fix addressing when original request has no 'to' attribute

---

changelog.html
src/java/com/reucon/openfire/plugin/archive/impl/MucMamPersistenceManager.java

The fix for #36 replaces the text value of the body element with other text. The replacement text needs to be properly escaped for XML.

fix #46: Replace body text with properly escaped data

---

changelog.html
plugin.xml
src/database/monitoring_db2.sql
src/database/monitoring_hsqldb.sql
src/database/monitoring_mysql.sql
src/database/monitoring_oracle.sql
src/database/monitoring_postgresql.sql
src/database/monitoring_sqlserver.sql
src/database/upgrade/5/monitoring_db2.sql
src/database/upgrade/5/monitoring_hsqldb.sql
src/database/upgrade/5/monitoring_mysql.sql
src/database/upgrade/5/monitoring_oracle.sql
src/database/upgrade/5/monitoring_postgresql.sql
src/database/upgrade/5/monitoring_sqlserver.sql
src/java/org/jivesoftware/openfire/archive/ArchivedMessage.java
src/java/org/jivesoftware/openfire/archive/ConversationManager.java

This commit replaces the mechanism to determine the next (unique) messageID value for rows in the ofMessageArchive table.
Instead of using count(*) to determine the next value, a sequence is used (as provided by Openfire's SequenceManager).
A database update script has been included that automatically initializes the sequence to the correct value, for databases that already have content.

fixes #58: Poor performance when adding messages to a large database.

---

src/java/org/jivesoftware/openfire/plugin/MonitoringPlugin.java

On pluginunload the features:
```
<feature var="urn:xmpp:mam:0" />
<feature var="urn:xmpp:mam:1" />
<feature var="urn:xmpp:mam:2" />
```
where not removed from disco list, so on plugin refresh (admin console) there were added again
this fix fixed this behaviour

Fix remove features on unload

---

changelog.html
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMucMessageLuceneQuery.java

This escapes the Lucene query, preventing parsing errors.

#91: Escape lucene query

---

src/java/org/jivesoftware/openfire/reporting/stats/StatsEngine.java

Added a continue statement after the Log.warn statement. This will skip the sample creation and update for the current statistic. It could still create a bunch of warn level log entries, but not the error level messages with stacktrace produced by the RrdException thrown by sample.update().

Fix issue #103 Log flooded with invalid sample time for statistics

---

changelog.html
plugin.xml
pom.xml
src/java/com/reucon/openfire/plugin/archive/ArchiveFactory.java
src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java
src/java/com/reucon/openfire/plugin/archive/impl/MucMamPersistenceManager.java
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMessageDatabaseQuery.java
src/java/com/reucon/openfire/plugin/archive/util/StanzaIDUtil.java
src/java/org/jivesoftware/openfire/archive/ConversationManager.java

By copying one method from Openfire 4.5.2, we can drop the required version back to 4.4.0.
When we eventually raise the minimum Openfire requirement, this PR should be undone.

fixes #118: Drop min required Openfire version back to 4.4.0

---

changelog.html
src/java/com/reucon/openfire/plugin/archive/impl/MucMamPersistenceManager.java

toJid for MUC will always be the exact bare JID. Anything that doesn't match we don't want, and DMs are accounted for by the toJidResource field.

fixes #157: Switch unnecessary LIKE on toJid for an exact match

---

changelog.html
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMessageDatabaseQuery.java
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMucMessageDatabaseQuery.java

Fixes #165 
[This](https://github.com/igniterealtime/openfire-monitoring-plugin/commit/db634ebc0e1f28fdb835d8f23ef7795baf74fa83) commit, sorting has been reversed whenever a `<before>` is present in a MAM query.
Rather than reintroduce the subquery to enforce the sort, this adds a list sort after retrieving the records.
Presently, this is still an ordering that relies on timestamps (as it always did) but given the granularity of the timestamp, the risks described in [XEP-0313§3.1](https://xmpp.org/extensions/xep-0313.html#archive_order) remain a low probability.

fixes #165: Guarantee sort order of results

---

changelog.html
src/java/com/reucon/openfire/plugin/archive/model/ArchivedMessage.java

Fixes #167 
Monitoring 2.2.0 enhanced some work on archiving full stanzas.
This fixes a bug where MAM requests attempts to use those stanza, not taking account for old archives that may have missing stanzas.

fixes #167: Deal with empty stanzas in db when processing MAM queries

---

changelog.html
src/database/monitoring_db2.sql
src/database/monitoring_hsqldb.sql
src/database/monitoring_mysql.sql
src/database/monitoring_oracle.sql
src/database/monitoring_postgresql.sql
src/database/monitoring_sqlserver.sql
src/database/upgrade/8/monitoring_db2.sql
src/database/upgrade/8/monitoring_hsqldb.sql
src/database/upgrade/8/monitoring_mysql.sql
src/database/upgrade/8/monitoring_oracle.sql
src/database/upgrade/8/monitoring_postgresql.sql
src/database/upgrade/8/monitoring_sqlserver.sql

The MySQL installation script was modified in release 2.2.0 to add a new column. This column should have been defined as NULL, but was defined as NOT NULL. The database update script (7) does is correctly (the problem only affects fresh installations that use the initial installation script).
This commit adds a new update script (number 8) that corrects the column definition for MySQL, and corrects the original installation script. It is otherwise a no-op for other databases.

fixes #175: Fix MySQL installation script

---

changelog.html
src/java/org/jivesoftware/openfire/archive/ArchiveIndexer.java
src/java/org/jivesoftware/openfire/archive/ArchiveSearcher.java

Using a term-based query for the JIDs of participants when searching through the Lucene index.

fixes #192: Return results for keyword and participant(s) combination query

---

src/java/org/jivesoftware/openfire/archive/Conversation.java
src/java/org/jivesoftware/openfire/archive/ConversationManager.java
src/java/org/jivesoftware/openfire/archive/ConversationParticipation.java
src/java/org/jivesoftware/openfire/archive/UserParticipations.java
src/java/org/jivesoftware/openfire/archive/XmlSerializer.java
src/java/org/jivesoftware/openfire/archive/cluster/GetConversationTask.java
src/java/org/jivesoftware/openfire/archive/cluster/GetConversationsTask.java
src/java/org/jivesoftware/openfire/archive/cluster/SendConversationEventsTask.java

This PR fixes #120 and #170.
Cluster tasks of this plugin now contain String representations of conversations, instead of of the Conversation objects themselves. This prevents the class loading errors observed in #120 and #170. Furthermore, this prevents similar problems that occured after the plugin was reloaded on one of the nodes.

Properly display conversations on junior node after plugin reload

---

changelog.html
plugin.xml
src/java/org/jivesoftware/openfire/archive/ConversationInfo.java
src/java/org/jivesoftware/openfire/archive/ConversationUtils.java
src/web/conversations.jsp

The admin page that shows active conversations should properly display group chats after an automatic update of its content.
When no conversations are active any more, then the table should contain a message to that effect.
fixes #206

Fixes for 'conversations' page (when auto-updating)

---

changelog.html
plugin.xml
pom.xml
src/i18n/monitoring_i18n.properties
src/java/org/jivesoftware/openfire/archive/ConversationManager.java
src/web/archive-search.jsp
src/web/archiving-settings.jsp
src/web/conversations.jsp
src/web/stats-dashboard.jsp
src/web/stats-reporter.jsp

The plugin cannot function properly when not all cluster nodes have the same version of the plugin installed.
The changes in this PR:
- Will show a warning on all plugin-provided admin console pages when it's detected that not every cluster member has the same version of the plugin installed
- Guards against failure to render the plugin-provided admin console pages. Note that no effort is made to ensure that proper data is displayed on those pages: when not all cluster nodes have the same plugin, that's impossible to guarantee.
The warning looks something like this. The screenshot also shows an impossible conversations count (that reflect data inconsistency).

fixes #162: handle plugin unavailable

---

changelog.html
src/java/org/jivesoftware/openfire/archive/ArchiveInterceptor.java

This is part 2 of a fix for Openfire blocklists OF-2189: 
https://github.com/igniterealtime/Openfire/pull/1795
fix: https://github.com/igniterealtime/openfire-monitoring-plugin/issues/184

fix: take care on privacy/block lists

---

changelog.html
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMessageLuceneQuery.java
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMucMessageLuceneQuery.java
src/java/org/jivesoftware/openfire/archive/ConversationManager.java
src/java/org/jivesoftware/openfire/archive/ConversationPDFServlet.java
src/java/org/jivesoftware/openfire/archive/ConversationUtils.java
src/java/org/jivesoftware/openfire/reporting/graph/GraphServlet.java
src/java/org/jivesoftware/openfire/reporting/stats/StatsAction.java
src/web/archive-conversation-participants.jsp
src/web/archive-search.jsp
src/web/archiving-settings.jsp
src/web/conversation-viewer.jsp
src/web/conversations.jsp
src/web/stats-dashboard.jsp
src/web/stats-reporter.jsp

Replace deprecated methods with the modern equivalents

fixes #235: Don't use deprecated Openfire methods

---

changelog.html
src/java/org/jivesoftware/openfire/plugin/MonitoringPlugin.java
src/java/org/jivesoftware/openfire/reporting/stats/StatsEngine.java

When another plugin provides a Statistic instance, that instance should be released when the provider unloads. Failing to do so will prevent that plugin's classloader from being destroyed. This can cause all kinds of unexpected side-effects.
This commit removes references to _all_ Statistic instances whenever _any_ plugin unloads. That's a buckshot, but the effects should be limited to missing stats around the time that a plugin gets unloaded/reloaded - which is expected to be very rare.

fixes #238: Release references provided by unloaded plugins

---

changelog.html
src/web/archiving-settings.jsp

The progress report that checks if Lucene indeces are rebuilt had a small error, causing the admin console to continuously display a message indicating that a rebuild was in progress.

fixes #249: Prevent continuous rebuild of Lucene index being reported

---

changelog.html
src/web/archiving-settings.jsp

The archiving settings page on the admin console erroneously displays "Search Indexes are rebuilding." all the time - even when message archiving isn't even enabled.
I'm actually unsure why this change works. I assume there's javascript/CSS magic that causes the problem.

fixes #377: Remove erroneous index confirmation message

---

.github/workflows/build.yml
changelog.html
plugin.xml
pom.xml
src/java/com/reucon/openfire/plugin/archive/impl/MessageIndexer.java
src/java/com/reucon/openfire/plugin/archive/impl/MucIndexer.java
src/java/org/jivesoftware/openfire/archive/ArchiveIndexer.java
src/java/org/jivesoftware/openfire/archive/ConversationEventsQueue.java
src/java/org/jivesoftware/openfire/archive/ConversationManager.java
src/java/org/jivesoftware/openfire/index/LuceneIndexer.java
src/java/org/jivesoftware/openfire/plugin/MonitoringPlugin.java
src/java/org/jivesoftware/openfire/reporting/stats/StatsEngine.java
src/java/org/jivesoftware/openfire/reporting/util/TaskEngine.java
src/web/archive-search.jsp

Replaced Openfire API usage that was deprecated in Openfire 4.8.0 and removed in 4.9.0.
This plugin is now compatible with Openfire 4.9.0 and requires 4.8.0 or later. No longer compatible with versions older than 4.8.0.
fixes #387

Fix compatibility issue with Openfire 4.9.0

---

changelog.html
plugin.xml

This adds a `priorToServerVersion` definition (which should be removed in a future version).
This should help prevent people running into #392

Branch 2.6 will not be compatible with Openfire 4.10.0

---

.github/workflows/build.yml
changelog.html
plugin.xml
pom.xml
src/java/org/jivesoftware/openfire/plugin/MonitoringPlugin.java

Fixes #339: Using Jetty 12's EE8 WebAppContext. Updated dependencies and release notes.

Fixes #339: Upgrade to be compatible with Openfire 5.0.0

---

src/java/com/reucon/openfire/plugin/archive/impl/AbstractPaginatedMamMucQuery.java
src/java/com/reucon/openfire/plugin/archive/impl/AbstractPaginatedMamQuery.java
src/java/com/reucon/openfire/plugin/archive/impl/MucMamPersistenceManager.java
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMessageDatabaseQuery.java
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMessageLuceneQuery.java
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMucMessageDatabaseQuery.java
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMucMessageFromOpenfireDatabaseQuery.java
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMucMessageFromOpenfireLuceneQuery.java
src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMucMessageLuceneQuery.java

The Monitoring Service plugin's XEP-0313: Message Archive Management implementation contains at least six similar query implementations. The code that is duplicated between them is moved to abstract classes, that the original code now inherits from. This reduces code duplication and makes it easier to add new query types.

Moving shared MAM Query representation into abstract class

---

changelog.html
src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java

Previously, it was possible, when querying an empty archive, to have a SQL statement that had the "WHERE RowNum" part of the clause, but not the "BETWEEN a AND b" part.
Fixes #363 - see issue for more details

fixes #363: For SQL Server, move entire WHERE clause together

---

changelog.html
src/java/org/jivesoftware/openfire/plugin/MonitoringPlugin.java

The NPE shown was an artifact of the page being processed without authentication in place. This should be prevented by the AuthCheckFilter.
Sadly, a naming collision prevents the AuthCheckFilter to operate on the Monitoring Service admin console pages.
This commit prevents the naming collision, by renaming the endpoint on which the public API for logs is exposed (from 'monitoring' to 'logs').
This is not an ideal solution, as it hides a deeper problem with regards to collision of web endpoints. Alas, I think this is the best that we can do without rewriting parts of Openfire (that may affect other plugins).

fixes #357: No longer show NPE on admin console after user session expired

---

changelog.html
pom.xml

By virtue of the upgrade of Jersey from 2.35 to 2.45 (in #401), the transient dependency of `jackson-database` got updated. This resolves the issue implicitly.
In this commit, a changelog entry is added, and an unused version identifier is removed.
This replaces PR #231

fixes #230: Jackson-database security issue

---

changelog.html
plugin.xml
pom.xml
src/database/monitoring_db2.sql
src/database/monitoring_hsqldb.sql
src/database/monitoring_mysql.sql
src/database/monitoring_oracle.sql
src/database/monitoring_postgresql.sql
src/database/monitoring_sqlserver.sql
src/database/upgrade/9/monitoring_db2.sql
src/database/upgrade/9/monitoring_hsqldb.sql
src/database/upgrade/9/monitoring_mysql.sql
src/database/upgrade/9/monitoring_oracle.sql
src/database/upgrade/9/monitoring_postgresql.sql
src/database/upgrade/9/monitoring_sqlserver.sql
src/java/com/reucon/openfire/plugin/archive/impl/MucIndexer.java
src/java/org/jivesoftware/openfire/archive/ArchiveIndexer.java
src/java/org/jivesoftware/openfire/archive/Conversation.java
src/java/org/jivesoftware/openfire/archive/ConversationDAO.java
src/java/org/jivesoftware/openfire/archive/ConversationEvent.java
src/java/org/jivesoftware/openfire/archive/ConversationManager.java
src/java/org/jivesoftware/openfire/archive/GroupConversationInterceptor.java
src/test/java/org/jivesoftware/openfire/archive/XmlSerializerTest.java

We can address both #369 and #370 by implementing the handling of the "clear chat history" event from Openfire. Openfire sends a "clear chat history" event in the following scenarios:
- A room is destroyed, and no chat history should be preserved.
- A "clear room history" command is issued during the lifetime of a chat room.
This intends to replace #408 
The approach in this PR differs from the one in 408 in that it does not attempt to introduce a new unique identifier for a room. Instead, an Openfire-provided identifier (`roomID`) is re-used. This intends to:
- better separates concerns: responsibility for generating a unique value now is located in only one piece of functionality (that pre-exists).
- avoids issues when the plugin was not loaded when a room was created
- reduces code …

#369 and #370: Add support for the clear chat room history event

---

changelog.html
src/java/com/reucon/openfire/plugin/archive/impl/MucIndexer.java

When iterating over all rows of a potentially large table, ensure that the database result set is configured to be 'linear' (forward-only and read-only).
This gives a better chance of the database driver to release all rows that have been iterated over, which prevents the fetch buffer to eventually include all rows (and potentially cause out-of-memory issues).

fixes #409: Prevent loading all archived messages in memory when indexing

---

changelog.html
pom.xml

Openfire 5.0.0 will no longer provide the commons-io library. This plugin makes use of that library.
In this commit, the commons-io library is included with the plugin itself.
fixes #415

Include commons-io library

---

changelog.html
src/java/com/reucon/openfire/plugin/archive/model/ArchivedMessage.java

When the monitoring plugin didn't store the entire stanza, it will attempt to reconstruct a stanza from the metadata that was stored.
When a message is a MUC message, the room JID rather than the real JIDs of the sender should be used in the reconstructed message.
fixes #418

When reconstructing MUC message, use room JID

---

changelog.html
plugin.xml
src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java
src/java/com/reucon/openfire/plugin/archive/impl/MucMamPersistenceManager.java

This duplicates the fix for #79, which was applied only to MUC archives.

fixes #365: Fixes error when using 'before' or 'after' with unrecognized value in personal archives
